### ISSUE TITLE
Default implementations for IPropertyCallback

### ISSUE THREAD

**Issue by Kovak** [ObliviousSpartan/SpartanWeaponry#3]
It would be nice if there were default implementations on all the IPropertyCallbacks so that a user would only have to override the methods they really wanted to rather than all of them.

**Comment by ObliviousSpartan** [comment]
See the class WeaponPropertyWithCallback in the api.weaponproperty package. What you want is there.

**Comment by Kovak** [comment]
This is useful, but what I mean is that if you do something like

```
public interface IIntegration {

    boolean isLoaded();

    default void mod_init() {
    }

    default void crafting_register(RegistryEvent.Register<IRecipe> event) {
    }
}
```

You can simplify your entire API and make it more legible and
